[[IgnoredVulns]]
id = "GHSA-8hc4-vh64-cxmj"
reason = "Axios URL is not user-controlled"

[[IgnoredVulns]]
id = "GHSA-952p-6rrq-rcjv"
reason = "It is a test dependency"

[[IgnoredVulns]]
id = "GHSA-gcx4-mw62-g8wm"
reason = "vulnerability outside project scope, url not present to do xss"

[[IgnoredVulns]]
id = "GHSA-64vr-g452-qvp3"
reason = "vulnerability outside project scope, url not present to do xss"

[[IgnoredVulns]]
id = "GHSA-9cwx-2883-4wfx"
reason = "vulnerability outside project scope, url not present to bypass access"